
name: Modified CI
jobs:
  Test:
    name: Test (${{ matrix.os }}, ${{ matrix.jdk }})
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        jdk:
        - 8
        include:
        - os: ubuntu-latest
          jdk: 21
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-Test (${{ matrix.os }}, ${{ matrix.jdk }}).csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/vertx-examples/vertx-examples', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-java-${{ matrix.jdk }}
    - run: touch optcd-3.txt
    - name: Checkout
      uses: actions/checkout@v2
    - run: touch optcd-4.txt
    - name: Install JDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.jdk }}
    - run: touch optcd-5.txt
    - name: Run tests
      run: mvn -q clean verify -B
    - run: touch optcd-6.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-Test (${{ matrix.os }}, ${{ matrix.jdk }})
        path: /home/runner/inotifywait-log-Test (${{ matrix.os }}, ${{ matrix.jdk
          }}).csv
'on':
- push
- workflow_dispatch
